const ULAM = [
    "Tokwa't Baboy",
    "Pork Menudo",
    "Tinolang Manok",
    "Sinaing na Tulingan",
    "Beef Kaldereta",
    "Sinigang na Bangus",
    "Adobong Manok",
    "Sinigang sa Miso",
    "Bangus Inihaw",
    "Bistek",
    "Adobong Sitaw",
    "Bulalo",
    "Pares",
    "Crispy Pata",
    "Patatas con Corned Beef",
    "Inasal na Manok",
    "Lechon",
    "Lechon Paksiw",
    "Afritada",
    "Ampalaya con Carne",
    "Pritong Galunggong",
    "Mechado",
    "Embutido",
    "Picadillo",
    "Pork Asado",
    "Pork Chop Steak",
    "Humba",
    "Paksiw na Isda",
    "Sotanghon with Patola",
    "Longganiza",
    "Chicken Tocino",
    "Patatim",
    "Adobong Pusit",
    "Estofado",
    "Bicol Express",
    "Ginataang Langka",
    "Laing",
    "Tofu Sisig",
    "Chicken Curry",
    "Fried Chicken",
    "Kare-kare",
    "Talong Steak",
    "Adobong Kangkong",
    "Pansit Bihon",
    "Shanghai",
    "Friday's Best (Monggo)",
    "Diningdeng",
    "Pork Barbeque",
    "Ginataang Kalabasa",
    "Binagoongan",
    "Tortang Talong",
    "Sinampalukang Manok",
    "Sinigang na Baboy",
    "Pritong Itlog",
    "Itlog na Maalat",
    "Swam na Mais",
    "Tuyo at Itlog",
    "Pansit Canton",
    "Beef Brocolli",
    "Bopis",
    "Chicken Nuggets",
    "Adobong Atay-Balunan",
    "Pinakbet",
    "Dinakdakan",
    "Ginisang Giniling",
    "Relyenong Bangus",
    "Sipo Egg",
    "Pangat na Bangus",
    "Kilawing Isda",
    "Burger Steak",
    "Pininyahang Manok",
    "Ginisang Sayote",
    "Ginisang Upo",
    "Creamy Lengua",
    "Nilagang Baka",
    "Ginisang Labanos",
    "Buttered Shrimp",
    "Ginataang Hipon",
    "Baked Tahong",
    "Chopsuey",
    "Chicken Sisig"
];